org.gradle.jvmargs=-Xmx2G
modName=MoogsBountifulStructures
minecraftVersion=1.20
modVersion=1.0.1
modId=mbs

# Publishing display customization
publishDisplayPrefix=MBS
publishDisplaySuffix=[UNIVERSAL]
publishingDisplayName=Moog's Bountiful Structures

# Publishing platform settings
modrinthProjectId=Qnb1HbfK
curseforgeProjectId=1499680
curseforgeProjectSlug=mbs-moogs-bountiful-structures
publishMcStart=1.20
publishMcEnd=1.20.6

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/1736/723/64/64/639105562499405210.png
discordBannerUrl=https://imgur.com/e9nLQ0G.png
discordEmbedColor=#804e50
