org.gradle.jvmargs=-Xmx2G
modName=MoogsBountifulStructures
minecraftVersion=1.21
modVersion=1.0.0
modId=mbs

# Publishing display customization
publishDisplayPrefix=MBS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=PLACEHOLDER
curseforgeProjectId=PLACEHOLDER
curseforgeProjectSlug=moogs-bountiful-structures
publishMcStart=1.21
publishMcEnd=1.21.11

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/869/885/64/64/638285724433169131.png
discordEmbedColor=#804e50
